// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ChoiceGroup = {
  /**
   * Valg-gruppen inneholder disse valgene
   */
  choices: Array<string> | string;
}
