// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Choices = import("./choices").Choices;
export type ConditionNumber = import("./condition-number").ConditionNumber;
export type CoreCommon = import("./core-common").CoreCommon;
export type Logical = import("./logical").Logical;
export type LogicalOperator = import("./logical-operator").LogicalOperator;
export type NextQuestionOrResult = import("./next-question-or-result").NextQuestionOrResult;
export type RequiredInputFeedbackText = import("./required-input-feedback-text").RequiredInputFeedbackText;
