// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BranchRadio = {
  /**
   * Valgtype
   */
  directOrRefChoices:
    | {
        /**
         * Selected
         */
        _selected: "direct";

        /**
         * Valg uten referanse
         */
        direct: {
          /**
           * Valg som fører til neste spørsmål eller resultat
           */
          choices: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "reference";

        /**
         * Valg med referanse
         */
        reference: {
          /**
           * Valg som fører til neste spørsmål eller resultat
           */
          choices: Array<string> | string;
        };
      };

  /**
   * Neste spørsmål eller resultat
   */
  nextQuestionOrResult: string;
}
