// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Logical = {
  /**
   * Kriterier for visning
   */
  displayCriteria: {
    /**
     * Logisk operator for denne boksen
     */
    "logical-operator"?: "and" | "or" | "not";


    answerOrLogic?: Array<
      | {
          /**
           * Selected
           */
          _selected: "answer";

          /**
           * Svar
           */
          answer: {
            /**
             * Logisk operator for denne boksen
             */
            logicalOperator?: "and" | "or" | "not";

            /**
             * Svar
             */
            answers: Array<string> | string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "logic";

          /**
           * Logisk uttrykk
           */
          logic: {
            /**
             * Logisk operator for denne boksen
             */
            logicalOperator?: "and" | "or" | "not";


            logic: Array<{
              /**
               * Logisk operator for denne boksen
               */
              logicalOperator?: "and" | "or" | "not";

              /**
               * Svar
               */
              answers: Array<string> | string;
            }>;
          };
        }
    >;
  };
}
