// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Question = {
  /**
   * Spørsmål
   */
  question: string;

  /**
   * Valgtype
   */
  choiceType:
    | {
        /**
         * Selected
         */
        _selected: "radio";

        /**
         * Radioknapper
         */
        radio: {
          /**
           * Grener
           */
          nextStep?: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "checkbox";

        /**
         * Sjekkboks
         */
        checkbox: {
          /**
           * Grener
           */
          nextStep?: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "number";

        /**
         * Tall
         */
        number: {
          /**
           * Grener
           */
          nextStep?: Array<string> | string;
        };
      };
}
