// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BranchCheckbox = import("./branch-checkbox").BranchCheckbox;
export type BranchNumber = import("./branch-number").BranchNumber;
export type BranchRadio = import("./branch-radio").BranchRadio;
export type ChoiceGroup = import("./choice-group").ChoiceGroup;
export type Choice = import("./choice").Choice;
export type Question = import("./question").Question;
export type ResultCalculator = import("./result-calculator").ResultCalculator;
export type ResultWithConditions = import("./result-with-conditions").ResultWithConditions;
export type Result = import("./result").Result;
export type Wizard = import("./wizard").Wizard;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.mattilsynet.wizard:branch-checkbox": BranchCheckbox;
      "no.mattilsynet.wizard:branch-number": BranchNumber;
      "no.mattilsynet.wizard:branch-radio": BranchRadio;
      "no.mattilsynet.wizard:choice-group": ChoiceGroup;
      "no.mattilsynet.wizard:choice": Choice;
      "no.mattilsynet.wizard:question": Question;
      "no.mattilsynet.wizard:result-calculator": ResultCalculator;
      "no.mattilsynet.wizard:result-with-conditions": ResultWithConditions;
      "no.mattilsynet.wizard:result": Result;
      "no.mattilsynet.wizard:wizard": Wizard;
    }
  }
}
