// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AnswerGroup = import("./answer-group").AnswerGroup;
export type Answer = import("./answer").Answer;
export type BranchCheckbox = import("./branch-checkbox").BranchCheckbox;
export type BranchNumber = import("./branch-number").BranchNumber;
export type BranchRadio = import("./branch-radio").BranchRadio;
export type Question = import("./question").Question;
export type ResultEngineResult = import("./result-engine-result").ResultEngineResult;
export type ResultEngine = import("./result-engine").ResultEngine;
export type Result = import("./result").Result;
export type Wizard = import("./wizard").Wizard;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.mattilsynet.wizard:answer-group": AnswerGroup;
      "no.mattilsynet.wizard:answer": Answer;
      "no.mattilsynet.wizard:branch-checkbox": BranchCheckbox;
      "no.mattilsynet.wizard:branch-number": BranchNumber;
      "no.mattilsynet.wizard:branch-radio": BranchRadio;
      "no.mattilsynet.wizard:question": Question;
      "no.mattilsynet.wizard:result-engine-result": ResultEngineResult;
      "no.mattilsynet.wizard:result-engine": ResultEngine;
      "no.mattilsynet.wizard:result": Result;
      "no.mattilsynet.wizard:wizard": Wizard;
    }
  }
}
