// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BranchNumber = {
  /**
   * Svaralternativer
   */
  directOrRefAnswers:
    | {
        /**
         * Selected
         */
        _selected: "direct";

        /**
         * Direktesvar
         */
        direct: {
          /**
           * Svar som fører til neste spørsmål eller resultat
           */
          answers: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "reference";

        /**
         * Referansesvar
         */
        reference: {
          /**
           * Svar som fører til neste spørsmål eller resultat
           */
          answers: Array<string> | string;
        };
      };

  /**
   * Neste spørsmål eller resultat
   */
  nextQuestionOrResult: string;

  /**
   * Betinget navigering totalsum
   */
  conditionalAnswerTotal?: {
    /**
     * Betingelse for tall-input
     */
    numberCondition:
      | {
          /**
           * Selected
           */
          _selected: "gt";

          /**
           * Større enn
           */
          gt: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "lt";

          /**
           * Mindre enn
           */
          lt: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "between";

          /**
           * Mellom
           */
          between: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "eq";

          /**
           * Lik
           */
          eq: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "neq";

          /**
           * Ulik
           */
          neq: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        };

    /**
     * Neste spørsmål eller resultat
     */
    nextQuestionOrResult: string;
  };

  /**
   * Betinget navigering
   */
  conditionalAnswer?: Array<{
    /**
     * Betingelse for tall-input
     */
    numberCondition:
      | {
          /**
           * Selected
           */
          _selected: "gt";

          /**
           * Større enn
           */
          gt: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "lt";

          /**
           * Mindre enn
           */
          lt: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "between";

          /**
           * Mellom
           */
          between: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "eq";

          /**
           * Lik
           */
          eq: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "neq";

          /**
           * Ulik
           */
          neq: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        };

    /**
     * Svar betingelsen gjelder for
     */
    answers: Array<string> | string;

    /**
     * Neste spørsmål eller resultat
     */
    nextQuestionOrResult: string;
  }>;
}
