// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BranchNumber = {
  /**
   * Valgtype
   */
  directOrRefChoices:
    | {
        /**
         * Selected
         */
        _selected: "direct";

        /**
         * Valg uten referanse
         */
        direct: {
          /**
           * Valg som fører til neste spørsmål eller resultat
           */
          choices: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "reference";

        /**
         * Valg med referanse
         */
        reference: {
          /**
           * Valg som fører til neste spørsmål eller resultat
           */
          choices: Array<string> | string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "referenceOutside";

        /**
         * Valg med referanse som ligger utenfor veiviseren
         */
        referenceOutside: {
          /**
           * Valg som fører til neste spørsmål eller resultat. Se info hvis tom
           */
          choices: Array<string> | string;
        };
      };

  /**
   * Neste spørsmål eller resultat
   */
  nextQuestionOrResult: string;

  /**
   * Betinget navigering totalsum
   */
  conditionalChoiceTotal?: {
    /**
     * Betingelse for tall-input
     */
    numberCondition:
      | {
          /**
           * Selected
           */
          _selected: "gt";

          /**
           * Større enn
           */
          gt: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "lt";

          /**
           * Mindre enn
           */
          lt: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "between";

          /**
           * Mellom
           */
          between: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "eq";

          /**
           * Lik
           */
          eq: {
            /**
             * Lik
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "neq";

          /**
           * Ulik
           */
          neq: {
            /**
             * Ulik
             */
            number?: number;
          };
        };

    /**
     * Neste spørsmål eller resultat
     */
    nextQuestionOrResult: string;
  };

  /**
   * Betinget navigering
   */
  conditionalChoice?: Array<{
    /**
     * Betingelse for tall-input
     */
    numberCondition:
      | {
          /**
           * Selected
           */
          _selected: "gt";

          /**
           * Større enn
           */
          gt: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "lt";

          /**
           * Mindre enn
           */
          lt: {
            /**
             * Mindre enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "between";

          /**
           * Mellom
           */
          between: {
            /**
             * Større enn
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "eq";

          /**
           * Lik
           */
          eq: {
            /**
             * Lik
             */
            number?: number;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "neq";

          /**
           * Ulik
           */
          neq: {
            /**
             * Ulik
             */
            number?: number;
          };
        };

    /**
     * Valg betingelsen gjelder for
     */
    choices: Array<string> | string;

    /**
     * Neste spørsmål eller resultat
     */
    nextQuestionOrResult: string;
  }>;
};
